#!/bin/bash
PROJECT=$1

cat <<EOF
---
zookeeper::heliostest::servers: 
  - zookeeper-1.$PROJECT.cloud.spotify.net
  - zookeeper-2.$PROJECT.cloud.spotify.net
  - zookeeper-3.$PROJECT.cloud.spotify.net
helios::master::zk_connect_string: zookeeper-1.$PROJECT.cloud.spotify.net:2181,zookeeper-2.$PROJECT.cloud.spotify.net:2181,zookeeper-3.$PROJECT.cloud.spotify.net:2181
helios::agent::zk_connect_string: zookeeper-1.$PROJECT.cloud.spotify.net:2181,zookeeper-2.$PROJECT.cloud.spotify.net:2181,zookeeper-3.$PROJECT.cloud.spotify.net:2181
EOF
