#!/bin/bash
PUPPET_BRANCH=drewc/helios-system-test
PROJECT=drewc
for i in 1 2 3
do   
    spcloud create \
      --project=$PROJECT \
      --name=zookeeper-$i \
      --branch=$PUPPET_BRANCH \
      --classes=zookeeper::heliostest
done

PROJECT=drewc
PUPPET_BRANCH=drewc/helios-system-test
for i in 1 2 3
do
    spcloud create \
      --project=$PROJECT \
      --name=helios-master-$i \
      --branch=$PUPPET_BRANCH \
      --classes=helios::master
done

PROJECT=drewc
ZK=$(echo $(for i in 1 2 3; do echo zookeeper-$i.${PROJECT}.cloud.spotify.net:2181; done) | sed 's/ /,/g')
helios-master --zk $ZK


PROJECT=drewc
PUPPET_BRANCH=drewc/helios-system-test
for i in 2 # 1 2 3
do
    spcloud create \
      --project=$PROJECT \
      --name=helios-agent-$i \
      --branch=$PUPPET_BRANCH \
      --dist=precise \
      --classes=helios::agent
done





helios-master -s ${PROJECT}.cloud.spotify.net --zk $ZK