#!/bin/bash -x
if [ "x$DOCKER_HOST" == "x" ]; then echo "DOCKER_HOST need to be set"; exit 1; fi

REPO=spotify/helios-solo
HELIOS_IMAGE=$REPO:latest

RUNNING=$(docker inspect -f '{{ .State.Running }}' helios-solo-container 2>/dev/null)

if [ "$RUNNING" == "true" ] &> /dev/null; then
	echo 'helios-solo already running'
	exit 1
fi

docker rm helios-solo-container &> /dev/null

eval $(PATH=.:$PATH helios-env)

docker run -it \
-e HELIOS_INTERACTIVE=1 \
-e DOCKER_HOST=$DOCKER_HOST \
-e HELIOS_NAME=solo.local. \
-e HOST_ADDRESS=$DOCKER_HOST_ADDRESS \
-p 5801:5801 \
--name helios-solo-container \
$HELIOS_IMAGE \
bash -l
