#!/bin/bash -e

NAME=spotify-helios
USER=$NAME
GROUP=$NAME
RUNDIR=/var/run/$NAME

DIST_USER=spotify-helios-dist
DIST_USER_HOME=/spotify/helios

. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
  configure)
    getent passwd $USER >/dev/null ||       adduser --quiet --system --group \
                                                --home $RUNDIR --no-create-home $USER
    [ -d $RUNDIR ] || mkdir -p $RUNDIR
    chown $USER:$GROUP $RUNDIR

    getent passwd $DIST_USER >/dev/null ||  adduser --quiet --system --ingroup $GROUP \
                                                --home $DIST_USER_HOME --no-create-home $DIST_USER --shell /bin/bash
    chown -R $DIST_USER:$GROUP $DIST_USER_HOME
    chmod 775 $DIST_USER_HOME
    ;;
  upgrade)
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    ;;
esac

db_stop

#DEBHELPER#

exit 0
