#!/bin/bash
echo -n "Spoticloud project name for nodes: [default $LOGNAME-helios] "
read PROJECT
if [ -z "$PROJECT" ]
then
  PROJECT=$LOGNAME-helios
fi

echo -n "Last chance to bail out!  Press enter to destroy the cluster at $PROJECT"
read FOO

for i in helios-master helios-agent zookeeper 
do
    for j in 1 2 3
    do
	spcloud destroy --name $i-$j --project $PROJECT --yes
    done
done
