#!/bin/bash
initctl stop docker

## Kill off any running containers
## Try nicely
killall lxc-start
sleep 10
## Kill with prejudice
killall -9 lxc-start

## Attempt to undo any aufs mounts
for i in $(cat /proc/mounts | grep '/var/lib/docker/aufs' | cut -d' ' -f2)
do
    umount $i
done

## Move all the container stuff out of the way
cd /var/lib/docker
DIRNAME=crud-$(date +%s)
mkdir $DIRNAME
mv aufs containers graph $DIRNAME

## Flush any iptables routes so we don't conflict when it comes back up
for i in PREROUTING INPUT OUTPUT DOCKER POSTROUTING
do
  iptables -tnat -F $i
done

## Start docker back up
initctl start docker

## Nuke the old container stuff
rm -rf $DIRNAME # may fail
