#!/bin/sh
if [ "$1" = configure ]; then
    # Make sure the helios user exists
    if ! getent passwd helios > /dev/null; then
        adduser --system --quiet --home /spotify/var/helios --no-create-home \
            --shell /bin/bash --group --gecos "Helios" helios
    fi

    # check validity of helios user and group
    if [ "`id -u helios`" -eq 0 ]; then
        echo "The helios user must not have uid 0 (root).
Please fix this and reinstall this package." >&2
        exit 1
    fi
    if [ "`id -g helios`" -eq 0 ]; then
        echo "The helios user must not have root as primary group.
Please fix this and reinstall this package." >&2
        exit 1
    fi
fi

# if already running, stop it first
initctl stop helios-master || true

initctl start helios-master
