#!/bin/sh
if [ "$1" = configure ]; then
    # Make sure the helios user exists
    if ! getent passwd helios > /dev/null; then
        adduser --system --quiet --home /var/lib/helios-master --no-create-home \
            --shell /bin/bash --group --gecos "Helios" helios
    fi

    # check validity of helios user and group
    if [ "`id -u helios`" -eq 0 ]; then
        echo "The helios user must not have uid 0 (root).
Please fix this and reinstall this package." >&2
        exit 1
    fi
    if [ "`id -g helios`" -eq 0 ]; then
        echo "The helios user must not have root as primary group.
Please fix this and reinstall this package." >&2
        exit 1
    fi
fi

# Start helios-master
if which initctl >/dev/null && initctl version | grep -q upstart; then
    # Using upstart
    initctl stop helios-master >/dev/null 2>&1 || true
    initctl start helios-master || true
else
    # Using SysV init scripts
    /etc/init.d/helios-master stop >/dev/null 2>&1 || true
    /etc/init.d/helios-master start || true
fi
